### ISSUE TITLE
Fix publish credentials

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s-otel4s#1]
It's still publishing to `io.christopherdavenport`.

**Comment by rossabaker** [comment]
Should be fixed by #27.

**Comment by NthPortal** [comment]
I think credentials still need to be put into the repository settings @rossabaker

**Comment by rossabaker** [comment]
Weird.  They're at the repository level, but it's definitely broken...

**Comment by rossabaker** [comment]
Looks like I just needed to merge #28.  The last main build published.
