### ISSUE TITLE
Proposal: relicense to Apache 2.0

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s-otel4s#5]
Most http4s projects and otel4s are Apache-2.0.

@ChristopherDavenport and I are the only two contributors as of ff447880c3bdef1c4476da62eb451421f06e0250, so nobody needs to argue about compatibility as long as we both consent.

**Comment by NthPortal** [comment]
wow, no need for my consent given #3? 😜 (yes I consent regardless)

**Comment by rossabaker** [comment]
You're absolutely right.  I focused only on what was already merged to reduce scope because most people hate license talk, but it's not clear that the [contributors' guide](https://github.com/http4s/http4s/blob/637f83177728b236b61563c53c8ef0fb8bd26d58/CONTRIBUTING.md#tldr-grant-of-license) applies to all repos, and more importantly, it was rude of me to overlook the outstanding work.  Thanks for speaking up!

**Comment by NthPortal** [comment]
I was kidding Ross, it's really not a big deal.

and besides, Apache 2 is my preferred license which I've used on pretty much all significant code projects

**Comment by ChristopherDavenport** [comment]
Approved
